package:
  name: sdk
  version: 0.0.1
  epoch: 0
  description: Development tools for melange and apko
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: Apache-2.0
  dependencies:
    runtime:
      - apk-tools
      - make
      - go
      - git
      - curl
      - bash
      - busybox
      - bubblewrap
      - tree
      - alpine-keys
      - jq
      - bincapz

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - build-base
      - busybox
      - go
      - git

pipeline:
  - runs: |
      set -x

      export DESTDIR="${{targets.destdir}}"
      export PATH="${DESTDIR}/usr/bin:/tmp/go/bin:${PATH}"

      # go setup
      export GOPATH="/tmp/go"
      mkdir -p "${GOPATH}"

      # goimports
      go install golang.org/x/tools/cmd/goimports@latest
      mkdir -p "${DESTDIR}/usr/bin"
      mv "${GOPATH}/bin/goimports" "${DESTDIR}/usr/bin"

      # apko
      git clone https://github.com/chainguard-dev/apko.git
      (cd apko && make apko install)

      # wolfictl
      git clone https://github.com/wolfi-dev/wolfictl.git
      (cd wolfictl && make wolfictl install)

      # melange
      melange_version=$(grep melange wolfictl/go.mod | cut '-d ' -f2)
      go install chainguard.dev/melange@$melange_version
      mv "${GOPATH}/bin/melange" "${DESTDIR}/usr/bin"

      #yam
      git clone https://github.com/chainguard-dev/yam.git
      cd yam
      go build -v -o  "${DESTDIR}/usr/bin/yam" .
      cd ..

      # sdk entrypoint
      cp mount/entrypoint.sh "${DESTDIR}/usr/bin/sdk"
