name: Reusable build workflow

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: '1.10.*'
          terraform_wrapper: false

      # Setup local registry
      - uses: chainguard-dev/actions/setup-registry@f0be69916b439d0fcced2451b23d0f27cd46d545 # v1.6.26
        if: inputs.registry == ''
        with:
          port: 5000

      # Auth to GitHub Container Registry (ghcr.io)
      - name: Login to registry
        if: inputs.registry != ''
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          echo "$GITHUB_TOKEN" | docker login \
            -u "$GITHUB_REPOSITORY_OWNER" \
            --password-stdin ghcr.io

      # Build and push image using terraform-provider-apko
      - name: Build image with apko/terraform
        env:
          TF_VAR_target_repository: ${{ inputs.registry != '' && inputs.registry || format('localhost:5000/{0}', inputs.image) }}
          IMAGE: ${{ inputs.image }}
        run: |
          set -x
          terraform init
          terraform apply -auto-approve -target="module.${IMAGE}"
