name: Reusable build workflow

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: '1.10.*'
          terraform_wrapper: false

      # Setup local registry
      - uses: chainguard-dev/actions/setup-registry@3b7bbeebc3a5d2bc37aa008350202651c32a26e1 # v1.6.22
        if: inputs.registry == ''
        with:
          port: 5000

      # Auth to GitHub Container Registry (ghcr.io)
      - name: Login to registry
        if: inputs.registry != ''
        run: |
          set -x
          echo "${{ github.token }}" | docker login \
            -u "${{ github.repository_owner }}" \
            --password-stdin ghcr.io

      # Build and push image using terraform-provider-apko
      - name: Build image with apko/terraform
        env:
          TF_VAR_target_repository: ${{ inputs.registry != '' && inputs.registry || format('localhost:5000/{0}', inputs.image) }}
        run: |
          set -x
          terraform init
          terraform apply -auto-approve -target=module.${{inputs.image}}
